title: Fizza Arif
logo: /assets/img/me.jpeg
description: I am a motivated and detail-oriented individual with a Google Cybersecurity Certificate and a passion for cybersecurity seeking an entry-level security analyst position. Possessing a strong foundation in cybersecurity principles, along with hands-on experience through practical projects and gaming modules, I am eager to contribute to safeguarding digital assets and mitigating security risks.
show_downlaods: true
theme: jekyll-theme-minimal
